<?php

namespace App\Filament\Resources\ProjectResource\Pages;

use App\Filament\Resources\ProjectResource;
use App\Models\Project;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Validation\ValidationException;

class CreateProject extends CreateRecord
{
    protected static string $resource = ProjectResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $check = false;
       // $status = $data['status'] ?? null;
        $license_number = $data['license_number'] ?? null;
        $licensing_authority_id = $data['licensing_authority_id'] ?? null;

        if (! empty($license_number) && ! empty($licensing_authority_id)) {
            $check = Project::query()->where([
                ['license_number','=', $license_number],
                ['licensing_authority_id', '=', $licensing_authority_id]
            ])->exists();
        }


        if ($check) {

            Notification::make()
                ->title(trans('resources.license_number_licensing_authority_exists'))
                ->danger()
                ->send();

            throw ValidationException::withMessages(['license number and licensing authority already exists']);

        } else {
            return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
        }

    }

    public function mksGetForm()
    {
        return $this->form;
    }
}
