<?php

namespace App\Filament\Resources\ActivityTypeResource\Pages;

use App\Filament\Resources\ActivityTypeResource;
use App\Models\ActivityArea;
use App\Models\ActivityType;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\CreateRecord;

class CreateActivityType extends CreateRecord
{
    protected static string $resource = ActivityTypeResource::class;

    public function create(bool $another = false): void
    {
        $name = $this->form->getState()['name'];
        $ckb = $name['ckb'];
        $activityAreaId = $this->form->getState()['activity_area_id'] ?? null;

        $check = ActivityType::query()
            ->where('activity_area_id', $activityAreaId)
            ->where('name->ckb', $ckb);

        if ($check->count() > 0) {

            Notification::make()
                ->danger()
                ->persistent()
                ->title(trans('resources.the_name_picked_before'))
                ->send();

            return;
        }

        parent::create($another); // TODO: Change the autogenerated stub
    }
}
