<?php

namespace App\Filament\Resources\ActivityAreaResource\Pages;

use App\Filament\Resources\ActivityAreaResource;
use App\Models\ActivityArea;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\CreateRecord;

class CreateActivityArea extends CreateRecord
{
    protected static string $resource = ActivityAreaResource::class;

    public function create(bool $another = false): void
    {
        $name = $this->form->getState()['name'];
        $ckb = $name['ckb'];

        $check = ActivityArea::query()
            ->where('name->ckb', $ckb);

        if ($check->count() > 0) {

            Notification::make()
                ->danger()
                ->persistent()
                ->title(trans('resources.the_name_picked_before'))
                ->send();

           return;
        }

        parent::create($another); // TODO: Change the autogenerated stub
    }
}




