<?php

namespace App\Filament\Widgets;

use App\Models\Project;
use Filament\Widgets\StatsOverviewWidget as BaseWidget;
use Filament\Widgets\StatsOverviewWidget\Stat;

class AllProjectsStatOverview extends BaseWidget
{
    protected function getColumns(): int
    {
        return 1; // TODO: Change the autogenerated stub
    }

    protected function getStats(): array
    {
        return [
            Stat::make(
                trans('widgets.total_projects'),
                Project::ignoreOrganizationForSuperAdmin()
                    ->where('show', 1)
                    ->count()
            )
        ];
    }
}
