<?php

namespace App\Filament\Widgets;

use App\Models\Project;
use App\Models\ProjectVariant;
use Filament\Widgets\StatsOverviewWidget as BaseWidget;
use Filament\Widgets\StatsOverviewWidget\Stat;
use Illuminate\Support\Number;

class ProjectsCapitalOverview extends BaseWidget
{
    protected function getColumns(): int
    {
        return 2; // TODO: Change the autogenerated stub
    }

    protected function getStats(): array
    {
        $capital_dinar = ProjectVariant::query()
            ->whereHas('project', fn ($q) => $q->where('show', 1)->where('status', 7)->ignoreOrganizationForSuperAdmin())
            ->sum('capital_dinar');
        $capital_dollar =  ProjectVariant::query()
            ->whereHas('project', fn ($q) => $q->where('show', 1)->where('status', 7)->ignoreOrganizationForSuperAdmin())
            ->sum('capital_dollar');

        return [
            Stat::make(
                trans('resources.project.finance.capital_dinar'),
                Number::currency($capital_dinar, 'IQD')
              //  number_format(is_numeric($capital_dinar) ? $capital_dinar : 0, 5)
            ),
            Stat::make(
                trans('resources.project.finance.capital_dollar'),
                Number::currency($capital_dollar)

            ),
        ];
    }
}
