<?php

namespace App\Filament\Resources\DepartmentResource\Pages;

use App\Filament\Resources\DepartmentResource;
use App\Models\Department;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\CreateRecord;

class CreateDepartment extends CreateRecord
{
    protected static string $resource = DepartmentResource::class;

    protected function getHeaderActions(): array
    {
        return [
            //
        ];
    }

    public function create(bool $another = false): void
    {
        $name = $this->form->getState()['name'];
        $ckb = $name['ckb'];

        $check = Department::query()
            ->where('name->ckb', $ckb);

        if ($check->count() > 0) {

            Notification::make()
                ->danger()
                ->persistent()
                ->title(trans('resources.the_name_picked_before'))
                ->send();

            return;
        }

        parent::create($another); // TODO: Change the autogenerated stub
    }
}
